spring.application.name=TpSpring-boot
spring.datasource.url= jdbc:mysql://localhost:3306/TpLy
spring.datasource.username= root
spring.datasource.password=Ndiaye05
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8086